"""add to posts user_id and author

Revision ID: 874bcb68c974
Revises: 29803400cc62
Create Date: 2025-01-14 13:05:14.363704
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874bcb68c974'
down_revision = '29803400cc62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_id', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
