"""add is_active, category

Revision ID: 96258385d3ac
Revises: d16cf0465f5f
Create Date: 2025-01-14 10:56:30.213450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96258385d3ac'
down_revision = 'd16cf0465f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('author', sa.String(length=100), nullable=False, default='None'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('author')
        batch_op.drop_column('category')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
